// Regenerates supabase/seed.sql from the bundled starter content: `npm run seed:generate`
// Each insert only runs when its table is empty, so the file is safe to run more than once.
import { writeFileSync } from "node:fs";
import { productTranslations } from "../src/data/product-translations";
import { sampleProducts } from "../src/data/products";
import { defaultSettings, sampleCertifications, samplePartners, sampleTeam, sampleTestimonials } from "../src/data/samples";

type Value = string | number | boolean | null | string[] | object;

const literal = (v: Value): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return `array[${v.map((x) => literal(x)).join(", ")}]::text[]`;
  if (typeof v === "object") return `${literal(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

function insert(table: string, rows: Record<string, Value>[]) {
  const columns = Object.keys(rows[0]);
  const values = rows.map((r) => `  (${columns.map((c) => literal(r[c])).join(", ")})`).join(",\n");
  return `insert into public.${table} (${columns.join(", ")})
select * from (values
${values}
) as v(${columns.join(", ")})
where not exists (select 1 from public.${table});
`;
}

/** Drops the local placeholder id so the database generates a UUID. */
const strip = <T extends { id: string }>(row: T) => {
  const copy: Partial<T> = { ...row };
  delete copy.id;
  return copy as Omit<T, "id">;
};

const products = sampleProducts.map((p, i) => ({
  slug: p.slug,
  name: p.name,
  category: p.category,
  grade: p.grade,
  summary: p.summary,
  description: p.description,
  image: p.image,
  gallery: p.gallery,
  origin: p.origin,
  specs: p.specs,
  packaging: p.packaging,
  moq: p.moq,
  featured: p.featured,
  sort_order: (i + 1) * 10,
  translations: productTranslations[p.slug] ?? {},
  // Specs and photos are placeholders until confirmed with Cao Gia.
  is_sample: true,
}));

const sql = `-- Generated by scripts/generate-seed.ts — do not edit by hand.

${insert("products", products)}
${insert("testimonials", sampleTestimonials.map(strip))}
${insert("partners", samplePartners.map(strip))}
${insert("certifications", sampleCertifications.map(strip))}
${insert("team_members", sampleTeam.map(strip))}
insert into public.site_settings (id, data)
values (1, ${literal(defaultSettings)})
on conflict (id) do nothing;
`;

writeFileSync("supabase/seed.sql", sql);
console.log("Wrote supabase/seed.sql");
